
package br.com.sascar.integracao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SasIntegraWS", targetNamespace = "http://webservice.web.integracao.sascar.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SasIntegraWS {


    /**
     * 
     * @param novaSenha
     * @param usuario
     * @param senhaAtual
     * @return
     *     returns java.lang.String
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "atualizarSenha", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.AtualizarSenha")
    @ResponseWrapper(localName = "atualizarSenhaResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.AtualizarSenhaResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/atualizarSenhaRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/atualizarSenhaResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/atualizarSenha/Fault/SasIntegraNotification")
    })
    public String atualizarSenha(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senhaAtual", targetNamespace = "")
        String senhaAtual,
        @WebParam(name = "novaSenha", targetNamespace = "")
        String novaSenha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param idCliente
     * @param usuario
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.Cliente>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterClientes", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterClientes")
    @ResponseWrapper(localName = "obterClientesResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterClientesResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterClientesRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterClientesResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterClientes/Fault/SasIntegraNotification")
    })
    public List<Cliente> obterClientes(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade,
        @WebParam(name = "idCliente", targetNamespace = "")
        Integer idCliente)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idMotorista
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.Motorista>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMotoristas", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMotoristas")
    @ResponseWrapper(localName = "obterMotoristasResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMotoristasResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMotoristasRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMotoristasResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMotoristas/Fault/SasIntegraNotification")
    })
    public List<Motorista> obterMotoristas(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade,
        @WebParam(name = "idMotorista", targetNamespace = "")
        Integer idMotorista)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idMotoristaVeiculo
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.MotoristaVeiculo>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMotoristasVeiculos", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMotoristasVeiculos")
    @ResponseWrapper(localName = "obterMotoristasVeiculosResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMotoristasVeiculosResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMotoristasVeiculosRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMotoristasVeiculosResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMotoristasVeiculos/Fault/SasIntegraNotification")
    })
    public List<MotoristaVeiculo> obterMotoristasVeiculos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade,
        @WebParam(name = "idMotoristaVeiculo", targetNamespace = "")
        Long idMotoristaVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.LayoutTecladoVeiculos>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterLayoutTecladoVeiculos", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutTecladoVeiculos")
    @ResponseWrapper(localName = "obterLayoutTecladoVeiculosResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutTecladoVeiculosResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutTecladoVeiculosRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutTecladoVeiculosResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutTecladoVeiculos/Fault/SasIntegraNotification")
    })
    public List<LayoutTecladoVeiculos> obterLayoutTecladoVeiculos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.LayoutGrupoPontos>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterLayoutGrupoPontos", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutGrupoPontos")
    @ResponseWrapper(localName = "obterLayoutGrupoPontosResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutGrupoPontosResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutGrupoPontosRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutGrupoPontosResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutGrupoPontos/Fault/SasIntegraNotification")
    })
    public List<LayoutGrupoPontos> obterLayoutGrupoPontos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.GrupoAtuador>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterGrupoAtuadores", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterGrupoAtuadores")
    @ResponseWrapper(localName = "obterGrupoAtuadoresResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterGrupoAtuadoresResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterGrupoAtuadoresRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterGrupoAtuadoresResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterGrupoAtuadores/Fault/SasIntegraNotification")
    })
    public List<GrupoAtuador> obterGrupoAtuadores(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param ticket
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.StatusComando>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterStatusComando", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterStatusComando")
    @ResponseWrapper(localName = "obterStatusComandoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterStatusComandoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterStatusComandoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterStatusComandoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterStatusComando/Fault/SasIntegraNotification")
    })
    public List<StatusComando> obterStatusComando(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "ticket", targetNamespace = "")
        Integer ticket)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param ticket
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.StatusComando>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterStatusComandoTicketSascar", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterStatusComandoTicketSascar")
    @ResponseWrapper(localName = "obterStatusComandoTicketSascarResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterStatusComandoTicketSascarResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterStatusComandoTicketSascarRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterStatusComandoTicketSascarResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterStatusComandoTicketSascar/Fault/SasIntegraNotification")
    })
    public List<StatusComando> obterStatusComandoTicketSascar(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "ticket", targetNamespace = "")
        Integer ticket)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.TipoComando>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterTipoComando", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterTipoComando")
    @ResponseWrapper(localName = "obterTipoComandoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterTipoComandoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterTipoComandoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterTipoComandoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterTipoComando/Fault/SasIntegraNotification")
    })
    public List<TipoComando> obterTipoComando(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.PacotePosicao>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacotePosicoes", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoes")
    @ResponseWrapper(localName = "obterPacotePosicoesResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoesResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoes/Fault/SasIntegraNotification")
    })
    public List<PacotePosicao> obterPacotePosicoes(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.PacotePosicao>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacotePosicoesRestricao", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoesRestricao")
    @ResponseWrapper(localName = "obterPacotePosicoesRestricaoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoesRestricaoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesRestricaoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesRestricaoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesRestricao/Fault/SasIntegraNotification")
    })
    public List<PacotePosicao> obterPacotePosicoesRestricao(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.PacotePosicaoRFNacional>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacotePosicoesRFNacional", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoesRFNacional")
    @ResponseWrapper(localName = "obterPacotePosicoesRFNacionalResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoesRFNacionalResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesRFNacionalRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesRFNacionalResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesRFNacional/Fault/SasIntegraNotification")
    })
    public List<PacotePosicaoRFNacional> obterPacotePosicoesRFNacional(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param quantidade
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacotePosicoesJSON", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoesJSON")
    @ResponseWrapper(localName = "obterPacotePosicoesJSONResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicoesJSONResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesJSONRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesJSONResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicoesJSON/Fault/SasIntegraNotification")
    })
    public List<String> obterPacotePosicoesJSON(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param idFinal
     * @param usuario
     * @param idInicio
     * @param quantidade
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacotePosicaoPorRangeJSON", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicaoPorRangeJSON")
    @ResponseWrapper(localName = "obterPacotePosicaoPorRangeJSONResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicaoPorRangeJSONResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoPorRangeJSONRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoPorRangeJSONResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoPorRangeJSON/Fault/SasIntegraNotification")
    })
    public List<String> obterPacotePosicaoPorRangeJSON(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idInicio", targetNamespace = "")
        Long idInicio,
        @WebParam(name = "idFinal", targetNamespace = "")
        Long idFinal,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param idFinal
     * @param usuario
     * @param idInicio
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.PacotePosicao>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacotePosicaoPorRange", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicaoPorRange")
    @ResponseWrapper(localName = "obterPacotePosicaoPorRangeResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicaoPorRangeResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoPorRangeRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoPorRangeResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoPorRange/Fault/SasIntegraNotification")
    })
    public List<PacotePosicao> obterPacotePosicaoPorRange(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idInicio", targetNamespace = "")
        Long idInicio,
        @WebParam(name = "idFinal", targetNamespace = "")
        Long idFinal,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @param dataInicio
     * @param dataFinal
     * @return
     *     returns java.util.List<br.com.sascar.integracao.PacotePosicao>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacotePosicaoHistorico", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicaoHistorico")
    @ResponseWrapper(localName = "obterPacotePosicaoHistoricoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacotePosicaoHistoricoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoHistoricoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoHistoricoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacotePosicaoHistorico/Fault/SasIntegraNotification")
    })
    public List<PacotePosicao> obterPacotePosicaoHistorico(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "dataInicio", targetNamespace = "")
        String dataInicio,
        @WebParam(name = "dataFinal", targetNamespace = "")
        String dataFinal,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.PacoteLocalizacao>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPacoteLocalizacao", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacoteLocalizacao")
    @ResponseWrapper(localName = "obterPacoteLocalizacaoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPacoteLocalizacaoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacoteLocalizacaoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacoteLocalizacaoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPacoteLocalizacao/Fault/SasIntegraNotification")
    })
    public List<PacoteLocalizacao> obterPacoteLocalizacao(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param tipoTeclado
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.MacroTd50Tmcd>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMacroTd50Tmcd", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTd50Tmcd")
    @ResponseWrapper(localName = "obterMacroTd50TmcdResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTd50TmcdResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd50TmcdRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd50TmcdResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd50Tmcd/Fault/SasIntegraNotification")
    })
    public List<MacroTd50Tmcd> obterMacroTd50Tmcd(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "tipoTeclado", targetNamespace = "")
        TipoTeclado tipoTeclado)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param tipoTeclado
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.MacroTd50TmcdDetalhado>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMacroTd50TmcdDetalhado", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTd50TmcdDetalhado")
    @ResponseWrapper(localName = "obterMacroTd50TmcdDetalhadoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTd50TmcdDetalhadoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd50TmcdDetalhadoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd50TmcdDetalhadoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd50TmcdDetalhado/Fault/SasIntegraNotification")
    })
    public List<MacroTd50TmcdDetalhado> obterMacroTd50TmcdDetalhado(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "tipoTeclado", targetNamespace = "")
        TipoTeclado tipoTeclado)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param satelital
     * @return
     *     returns java.util.List<br.com.sascar.integracao.MacroTd40>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMacroTd40", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTd40")
    @ResponseWrapper(localName = "obterMacroTd40Response", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTd40Response")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd40Request", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd40Response", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTd40/Fault/SasIntegraNotification")
    })
    public List<MacroTd40> obterMacroTd40(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "satelital", targetNamespace = "")
        boolean satelital)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.MacroTms3>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMacroTms3", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTms3")
    @ResponseWrapper(localName = "obterMacroTms3Response", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMacroTms3Response")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTms3Request", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTms3Response", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMacroTms3/Fault/SasIntegraNotification")
    })
    public List<MacroTms3> obterMacroTms3(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @return
     *     returns java.util.List<br.com.sascar.integracao.MascaraDispositivo>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMascaraDispositivos", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMascaraDispositivos")
    @ResponseWrapper(localName = "obterMascaraDispositivosResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMascaraDispositivosResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMascaraDispositivosRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMascaraDispositivosResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMascaraDispositivos/Fault/SasIntegraNotification")
    })
    public List<MascaraDispositivo> obterMascaraDispositivos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param layout
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.Layout>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterLayout", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayout")
    @ResponseWrapper(localName = "obterLayoutResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayout/Fault/SasIntegraNotification")
    })
    public List<Layout> obterLayout(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "layout", targetNamespace = "")
        TipoLayout layout)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param layout
     * @param senha
     * @param dataReferencia
     * @param usuario
     * @param idLayout
     * @return
     *     returns java.util.List<br.com.sascar.integracao.LayoutDetalhado>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterLayoutDetalhado", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutDetalhado")
    @ResponseWrapper(localName = "obterLayoutDetalhadoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutDetalhadoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutDetalhadoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutDetalhadoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutDetalhado/Fault/SasIntegraNotification")
    })
    public List<LayoutDetalhado> obterLayoutDetalhado(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "layout", targetNamespace = "")
        TipoLayout layout,
        @WebParam(name = "idLayout", targetNamespace = "")
        Integer idLayout,
        @WebParam(name = "dataReferencia", targetNamespace = "")
        String dataReferencia)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @param quantidade
     * @return
     *     returns java.util.List<br.com.sascar.integracao.Veiculo>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterVeiculos", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterVeiculos")
    @ResponseWrapper(localName = "obterVeiculosResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterVeiculosResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterVeiculosRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterVeiculosResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterVeiculos/Fault/SasIntegraNotification")
    })
    public List<Veiculo> obterVeiculos(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "quantidade", targetNamespace = "")
        Integer quantidade,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.PontoReferencia>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterPontosReferencia", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPontosReferencia")
    @ResponseWrapper(localName = "obterPontosReferenciaResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterPontosReferenciaResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPontosReferenciaRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPontosReferenciaResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterPontosReferencia/Fault/SasIntegraNotification")
    })
    public List<PontoReferencia> obterPontosReferencia(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.SequenciamentoEvento>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterSequenciamentoEvento", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterSequenciamentoEvento")
    @ResponseWrapper(localName = "obterSequenciamentoEventoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterSequenciamentoEventoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterSequenciamentoEventoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterSequenciamentoEventoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterSequenciamentoEvento/Fault/SasIntegraNotification")
    })
    public List<SequenciamentoEvento> obterSequenciamentoEvento(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @return
     *     returns br.com.sascar.integracao.Mensagem
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterMensagemPortal", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMensagemPortal")
    @ResponseWrapper(localName = "obterMensagemPortalResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterMensagemPortalResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMensagemPortalRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMensagemPortalResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterMensagemPortal/Fault/SasIntegraNotification")
    })
    public Mensagem obterMensagemPortal(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @return
     *     returns br.com.sascar.integracao.Telemetria
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterTelemetriaPortal", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterTelemetriaPortal")
    @ResponseWrapper(localName = "obterTelemetriaPortalResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterTelemetriaPortalResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterTelemetriaPortalRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterTelemetriaPortalResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterTelemetriaPortal/Fault/SasIntegraNotification")
    })
    public Telemetria obterTelemetriaPortal(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param latitude
     * @param usuario
     * @param longitude
     * @return
     *     returns br.com.sascar.integracao.EnderecoPosicao
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterEnderecoPosicao", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterEnderecoPosicao")
    @ResponseWrapper(localName = "obterEnderecoPosicaoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterEnderecoPosicaoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterEnderecoPosicaoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterEnderecoPosicaoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterEnderecoPosicao/Fault/SasIntegraNotification")
    })
    public EnderecoPosicao obterEnderecoPosicao(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "latitude", targetNamespace = "")
        String latitude,
        @WebParam(name = "longitude", targetNamespace = "")
        String longitude)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @return
     *     returns boolean
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verificarVeiculoIntegrado", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.VerificarVeiculoIntegrado")
    @ResponseWrapper(localName = "verificarVeiculoIntegradoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.VerificarVeiculoIntegradoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/verificarVeiculoIntegradoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/verificarVeiculoIntegradoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/verificarVeiculoIntegrado/Fault/SasIntegraNotification")
    })
    public boolean verificarVeiculoIntegrado(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @return
     *     returns java.util.List<br.com.sascar.integracao.LayoutAcaoEmbarcadaAVD>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterLayoutAcaoEmbarcadaAVD", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutAcaoEmbarcadaAVD")
    @ResponseWrapper(localName = "obterLayoutAcaoEmbarcadaAVDResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterLayoutAcaoEmbarcadaAVDResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutAcaoEmbarcadaAVDRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutAcaoEmbarcadaAVDResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterLayoutAcaoEmbarcadaAVD/Fault/SasIntegraNotification")
    })
    public List<LayoutAcaoEmbarcadaAVD> obterLayoutAcaoEmbarcadaAVD(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @param pontosRef
     * @return
     *     returns br.com.sascar.integracao.LogComando
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "comandoEmbarquePontoDiario", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ComandoEmbarquePontoDiario")
    @ResponseWrapper(localName = "comandoEmbarquePontoDiarioResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ComandoEmbarquePontoDiarioResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/comandoEmbarquePontoDiarioRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/comandoEmbarquePontoDiarioResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/comandoEmbarquePontoDiario/Fault/SasIntegraNotification")
    })
    public LogComando comandoEmbarquePontoDiario(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo,
        @WebParam(name = "pontosRef", targetNamespace = "")
        String pontosRef)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param idEventoList
     * @param usuario
     * @param idVeiculo
     * @param dataInicio
     * @param dataFinal
     * @return
     *     returns java.util.List<br.com.sascar.integracao.EventoTelemetria>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterEventoTelemetriaIntegracao", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterEventoTelemetriaIntegracao")
    @ResponseWrapper(localName = "obterEventoTelemetriaIntegracaoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterEventoTelemetriaIntegracaoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterEventoTelemetriaIntegracaoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterEventoTelemetriaIntegracaoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterEventoTelemetriaIntegracao/Fault/SasIntegraNotification")
    })
    public List<EventoTelemetria> obterEventoTelemetriaIntegracao(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "dataInicio", targetNamespace = "")
        String dataInicio,
        @WebParam(name = "dataFinal", targetNamespace = "")
        String dataFinal,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo,
        @WebParam(name = "idEventoList", targetNamespace = "")
        List<Integer> idEventoList)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @param dataInicio
     * @param dataFinal
     * @return
     *     returns java.util.List<br.com.sascar.integracao.DeltaTelemetria>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterDeltaTelemetriaIntegracao", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterDeltaTelemetriaIntegracao")
    @ResponseWrapper(localName = "obterDeltaTelemetriaIntegracaoResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterDeltaTelemetriaIntegracaoResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterDeltaTelemetriaIntegracaoRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterDeltaTelemetriaIntegracaoResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterDeltaTelemetriaIntegracao/Fault/SasIntegraNotification")
    })
    public List<DeltaTelemetria> obterDeltaTelemetriaIntegracao(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "dataInicio", targetNamespace = "")
        String dataInicio,
        @WebParam(name = "dataFinal", targetNamespace = "")
        String dataFinal,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param telemetriaParametrizacao
     * @param usuario
     * @param idVeiculo
     * @return
     *     returns java.util.List<br.com.sascar.integracao.ComandoTelemetriaRetorno>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enviarParametrizacaoTelemetria", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.EnviarParametrizacaoTelemetria")
    @ResponseWrapper(localName = "enviarParametrizacaoTelemetriaResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.EnviarParametrizacaoTelemetriaResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/enviarParametrizacaoTelemetriaRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/enviarParametrizacaoTelemetriaResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/enviarParametrizacaoTelemetria/Fault/SasIntegraNotification")
    })
    public List<ComandoTelemetriaRetorno> enviarParametrizacaoTelemetria(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo,
        @WebParam(name = "telemetriaParametrizacao", targetNamespace = "")
        TelemetriaConfiguracao telemetriaParametrizacao)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param idVeiculo
     * @return
     *     returns java.util.List<br.com.sascar.integracao.DadosAdicionais>
     * @throws SasIntegraNotification
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterDadosAdicionais", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterDadosAdicionais")
    @ResponseWrapper(localName = "obterDadosAdicionaisResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.ObterDadosAdicionaisResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterDadosAdicionaisRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterDadosAdicionaisResponse", fault = {
        @FaultAction(className = SasIntegraNotification.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/obterDadosAdicionais/Fault/SasIntegraNotification")
    })
    public List<DadosAdicionais> obterDadosAdicionais(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        Integer idVeiculo)
        throws SasIntegraNotification
    ;

    /**
     * 
     * @param senha
     * @param dataPosicaoFinal
     * @param ticket
     * @param usuario
     * @param idVeiculo
     * @param dataPosicaoInicial
     * @param placa
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitarEventosCaixaPreta", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.SolicitarEventosCaixaPreta")
    @ResponseWrapper(localName = "solicitarEventosCaixaPretaResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.SolicitarEventosCaixaPretaResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/solicitarEventosCaixaPretaRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/solicitarEventosCaixaPretaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/solicitarEventosCaixaPreta/Fault/Exception")
    })
    public String solicitarEventosCaixaPreta(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        String idVeiculo,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "dataPosicaoInicial", targetNamespace = "")
        String dataPosicaoInicial,
        @WebParam(name = "dataPosicaoFinal", targetNamespace = "")
        String dataPosicaoFinal,
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket)
        throws Exception_Exception
    ;

    /**
     * 
     * @param senha
     * @param dataPosicao
     * @param usuario
     * @param idVeiculo
     * @param placa
     * @return
     *     returns br.com.sascar.integracao.CaixaPretaList
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperarEventosCaixaPreta", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.RecuperarEventosCaixaPreta")
    @ResponseWrapper(localName = "recuperarEventosCaixaPretaResponse", targetNamespace = "http://webservice.web.integracao.sascar.com.br/", className = "br.com.sascar.integracao.RecuperarEventosCaixaPretaResponse")
    @Action(input = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/recuperarEventosCaixaPretaRequest", output = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/recuperarEventosCaixaPretaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservice.web.integracao.sascar.com.br/SasIntegraWS/recuperarEventosCaixaPreta/Fault/Exception")
    })
    public CaixaPretaList recuperarEventosCaixaPreta(
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        String senha,
        @WebParam(name = "placa", targetNamespace = "")
        String placa,
        @WebParam(name = "idVeiculo", targetNamespace = "")
        String idVeiculo,
        @WebParam(name = "dataPosicao", targetNamespace = "")
        String dataPosicao)
        throws Exception_Exception
    ;

}
